apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pillguide
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pillguide/manifest.git
    targetRevision: main
    path: pillguide
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: pillguide
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
